### ISSUE TITLE
Use HTTP correctly

### ISSUE THREAD

**Issue by divarvel** [drouarb/nodejs-mongodb-demo#1]
To create a value:

    POST /values

With the content in the body as form-urlencoded or JSON

To delete a value

    DELETE /values/:id

**Comment by drouarb** [comment]
Fixed in f2198824f8ce6635420440f48e8e550efd8d00d1, 317c88e24e7350f9284b389f34d40e8c916ef6fd and 9f94cc0d412ee7a13ca78986d534728c9189ec43

**Comment by divarvel** [comment]
It's not fixed yet.

**Comment by drouarb** [comment]
FIxed in 85f84f745e483ef5913c1bd5f9ff8e556a1df34d
